config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  #ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  post 'search' => 'searches#search'
  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user.id)
    # redirect_to request.referer
    render 'replace_relationships'
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user.id)
    # redirect_to request.referer
    render 'replace_relationships'
  end

  # フォロー一覧
  def followings
    @user = User.find(params[:user_id])
    @other_users = @user.followings
  end

  # フォロワー一覧
  def followers
    @user = User.find(params[:user_id])
    @other_users = @user.followers
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow-btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, remote: true %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, remote: true %>
  <% end %>
<% end %>

app/views/relationships/_followers-counter.html.erb
フォロワー数: <%= user.followers.count %>

app/views/relationships/_followings-counter.html.erb
フォロー数: <%= user.followings.count %>

app/views/relationships/_userInfo_follow-btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, remote: true, class: 'btn btn-info' %>
  <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, remote: true, class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/relationships/_userInfo_followers-counter.html.erb
<%= link_to user_followers_path(user) do %>
  <%= user.followers.count %>
<% end %>

app/views/relationships/_userInfo_followings-counter.html.erb
<%= link_to user_followings_path(user) do %>
  <%= user.followings.count %>
<% end %>

app/views/relationships/create.js.erb
$(".followings-count-" + <%= @user.id.to_s %>).html("<%= j(render 'relationships/followings-counter', user: @user) %>");
$(".followers-count-" + <%= @user.id.to_s %>).html("<%= j(render 'relationships/followers-counter', user: @user) %>");
$(".relationship-btn-" + <%= @user.id.to_s %>).html("<%= j(render 'relationships/follow-btn', user: @user) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>

<% if @other_users.exists? %>
  <%= render 'users/index', users: @other_users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>

<% if @other_users.exists? %>
  <%= render 'users/index', users: @other_users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/replace_relationships.js.erb
<!-- 一覧表示箇所 -->
$(".followings-count-" + <%= current_user.id.to_s %>).html("<%= j(render 'relationships/followings-counter', user: current_user) %>");
$(".followers-count-" + <%= @user.id.to_s %>).html("<%= j(render 'relationships/followers-counter', user: @user) %>");
$(".relationship-btn-" + <%= @user.id.to_s %>).html("<%= j(render 'relationships/follow-btn', user: @user) %>");
<!-- UserInfo箇所-->
$(".userInfo_followings-count").html("<%= j(render 'relationships/userInfo_followings-counter', user: @user) %>");
$(".userInfo_followers-count").html("<%= j(render 'relationships/userInfo_followers-counter', user: @user) %>");
$(".userInfo_relationship-btn").html("<%= j(render 'relationships/userInfo_follow-btn', user: @user) %>");